/**
 * Films API
 * This is a simple API for managing films.  We are going to create a CRUD API for films.  We will also cover the following topics: * Result pagination * Security (Authentication and Authorization)  We will use a simple **Film** model with the following fields: * ID * Title * Length * MoodType 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ModelError { 
    /**
     * The error message
     */
    message: string;
}